# Setup phase containers - only used during initial cluster setup
# These containers are automatically removed after successful initialization

services:
  # Create the MongoDB keyfile first (must run before MongoDB containers)
  keyfile-init:
    image: busybox
    command: >
      sh -c "
      echo 'Creating dynamic keyfile...' &&
      dd if=/dev/urandom bs=1 count=700 2>/dev/null | base64 | tr -d '=+/' | cut -c1-700 > /shared/mongodb-key &&
      chmod 600 /shared/mongodb-key &&
      chown 1001:0 /shared/mongodb-key &&
      echo 'Keyfile created successfully (length:' $$(wc -c < /shared/mongodb-key) 'bytes)'
      "
    volumes:
      - shared-keyfile:/shared
    networks:
      - mongo-net
    restart: "no"

  # MongoDB initialization helper - runs once to set up the replica set (setup phase only)
  mongo-setup:
    image: percona/percona-server-mongodb:6.0-amd64
    depends_on:
      keyfile-init:
        condition: service_completed_successfully
      mongodb1:
        condition: service_healthy
      mongodb2:
        condition: service_healthy
      mongodb3:
        condition: service_healthy
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - mongo-net
    volumes:
      # Override the image's /data/db volume to prevent anonymous volume creation
      - /tmp/setup-temp:/data/db
      - shared-keyfile:/shared
    command: >
      bash -c "
        echo 'Waiting for MongoDB instances to be ready...' &&
        sleep 10 &&
        echo 'Getting configuration for replica set...' &&
        MONGODB1_HOST='${MONGODB1_HOST:-mongodb1}' &&
        MONGODB2_HOST='${MONGODB2_HOST:-mongodb2}' &&
        MONGODB3_HOST='${MONGODB3_HOST:-mongodb3}' &&
        MONGODB1_PORT='${FORWARD_MONGODB1_PORT}' &&
        MONGODB2_PORT='${FORWARD_MONGODB2_PORT}' &&
        MONGODB3_PORT='${FORWARD_MONGODB3_PORT}' &&
        echo \"Configuration: Primary=\$$MONGODB1_HOST:\$$MONGODB1_PORT, Secondary1=\$$MONGODB2_HOST:\$$MONGODB2_PORT, Secondary2=\$$MONGODB3_HOST:\$$MONGODB3_PORT\" &&
        echo 'Initializing replica set with consistent port mapping...' &&
        echo 'NOTE: Each MongoDB instance runs on its assigned port both internally and externally' &&
        mongosh --host \$$MONGODB1_HOST:\$$MONGODB1_PORT -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --eval \"
          rs.initiate({
            _id: 'rs',
            version: 1,
            members: [
              { _id: 0, host: '\$$MONGODB1_HOST:\$$MONGODB1_PORT', priority: 1000 },
              { _id: 1, host: '\$$MONGODB2_HOST:\$$MONGODB2_PORT', priority: 999 },
              { _id: 2, host: '\$$MONGODB3_HOST:\$$MONGODB3_PORT', priority: 998 }
            ]
          });
        \" &&
        echo 'Replica set initialized with consistent port mapping!' &&
        echo 'Verifying configuration...' &&
        mongosh --host \$$MONGODB1_HOST:\$$MONGODB1_PORT -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --eval \"
          console.log('Replica Set Configuration:');
          rs.config().members.forEach(function(member) {
            console.log('  Member ' + member._id + ': ' + member.host);
          });
          console.log('');
          console.log('✅ Client redirection will now work correctly!');
          console.log('Each node runs on its assigned port both internally and externally.');
        \" &&
        echo 'Cluster setup completed successfully!'
      "
    restart: "no"

# Note: volumes and networks are defined in docker-compose.yml
