services:
  mongodb1:
    image: percona/percona-server-mongodb:6.0-amd64
    hostname: ${MONGODB1_HOST:-mongodb1}
    networks:
      - mongo-net
    ports:
      - "${FORWARD_MONGODB1_PORT}:${FORWARD_MONGODB1_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_PORT: ${FORWARD_MONGODB1_PORT}
    volumes:
      - mongo1_db:/data/db
      - mongo1_configdb:/data/configdb
      - shared-keyfile:/etc/mongo:ro
    command: 
      - --bind_ip_all
      - --replSet
      - rs
      - --keyFile
      - /etc/mongo/mongodb-key
      - --port
      - ${FORWARD_MONGODB1_PORT}
    healthcheck:
      test: ["CMD", "mongosh", "--port", "${FORWARD_MONGODB1_PORT}", "--eval", "db.runCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mongodb2:
    image: percona/percona-server-mongodb:6.0-amd64
    hostname: ${MONGODB2_HOST:-mongodb2}
    networks:
      - mongo-net
    ports:
      - "${FORWARD_MONGODB2_PORT}:${FORWARD_MONGODB2_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_PORT: ${FORWARD_MONGODB2_PORT}
    volumes:
      - mongo2_db:/data/db
      - mongo2_configdb:/data/configdb
      - shared-keyfile:/etc/mongo:ro
    command:
      - --bind_ip_all
      - --replSet
      - rs
      - --keyFile
      - /etc/mongo/mongodb-key
      - --port
      - ${FORWARD_MONGODB2_PORT}
    healthcheck:
      test: ["CMD", "mongosh", "--port", "${FORWARD_MONGODB2_PORT}", "--eval", "db.runCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mongodb3:
    image: percona/percona-server-mongodb:6.0-amd64
    hostname: ${MONGODB3_HOST:-mongodb3}
    networks:
      - mongo-net
    ports:
      - "${FORWARD_MONGODB3_PORT}:${FORWARD_MONGODB3_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_PORT: ${FORWARD_MONGODB3_PORT}
    volumes:
      - mongo3_db:/data/db
      - mongo3_configdb:/data/configdb
      - shared-keyfile:/etc/mongo:ro
    command:
      - --bind_ip_all
      - --replSet
      - rs
      - --keyFile
      - /etc/mongo/mongodb-key
      - --port
      - ${FORWARD_MONGODB3_PORT}
    healthcheck:
      test: ["CMD", "mongosh", "--port", "${FORWARD_MONGODB3_PORT}", "--eval", "db.runCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  mongo1_db: {}
  mongo1_configdb: {}
  mongo2_db: {}
  mongo2_configdb: {}
  mongo3_db: {}
  mongo3_configdb: {}
  shared-keyfile: {}

networks:
  mongo-net:
    driver: bridge
