version: "3"
name: mongo-cluster
services:
  mongodb1:
    # build: .
    image: blackorder/mongo-cluster:latest
    restart: always
    hostname: mongodb1
    ports:
      - '${FORWARD_MONGODB_PORT:-27017}:27017'
    volumes:
      - mongo1_db:/data/db
      - mongo1_configdb:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - cluster_subnet
      - development
    environment:
      MONGODB_CLUSTER_HOSTS: ${MONGODB_CLUSTER_HOSTS:?err}
      MONGODB_CLUSTER_KEY: ${MONGODB_CLUSTER_KEY:?err}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:?err}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:?err}

  mongodb2:
    # build: .
    image: blackorder/mongo-cluster:latest
    restart: always
    hostname: mongodb2
    volumes:
      - mongo2_db:/data/db
      - mongo2_configdb:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - cluster_subnet
      - development
    environment:
      MONGODB_CLUSTER_KEY: ${MONGODB_CLUSTER_KEY:?err}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:?err}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:?err}

  mongodb3:
    # build: .
    image: blackorder/mongo-cluster:latest
    restart: always
    hostname: mongodb3
    volumes:
      - mongo3_db:/data/db
      - mongo3_configdb:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - cluster_subnet
      - development
    environment:
      MONGODB_CLUSTER_KEY: ${MONGODB_CLUSTER_KEY:?err}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:?err}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:?err}
      
  mongo-express:
    image: mongo-express:latest
    restart: always
    hostname: mongo-express
    ports:
      - '${FORWARD_MONGODB_EXPRESS_PORT:-8081}:8081'
    networks:
      - cluster_subnet
      - development
    depends_on:
      mongodb1:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME:?err}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD:?err}
      ME_CONFIG_MONGODB_URL: 'mongodb://${MONGODB_USERNAME:?err}:${MONGODB_PASSWORD:?err}@${MONGODB_CLUSTER_HOSTS:?err}/?replicaSet=rs'
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_USERNAME:?err}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_PASSWORD:?err}

networks:
  development:
    external: true
  cluster_subnet:
    driver: bridge
volumes:
  mongo1_db: {}
  mongo1_configdb: {}
  mongo2_db: {}
  mongo2_configdb: {}
  mongo3_db: {}
  mongo3_configdb: {}
