name: mongo-cluster

services:
  mongodb1:
    image: percona/percona-server-mongodb:6.0-amd64
    hostname: mongodb1
    ports:
      - "${FORWARD_MONGODB1_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo1_db:/data/db
      - mongo1_configdb:/data/configdb
      - shared-keyfile:/etc/mongo:ro
    command: 
      - --bind_ip_all
      - --replSet
      - rs
      - --keyFile
      - /etc/mongo/mongodb-key
    networks:
      - mongo-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mongodb2:
    image: percona/percona-server-mongodb:6.0-amd64
    hostname: mongodb2
    ports:
      - "${FORWARD_MONGODB2_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo2_db:/data/db
      - mongo2_configdb:/data/configdb
      - shared-keyfile:/etc/mongo:ro
    command:
      - --bind_ip_all
      - --replSet
      - rs
      - --keyFile
      - /etc/mongo/mongodb-key
    networks:
      - mongo-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mongodb3:
    image: percona/percona-server-mongodb:6.0-amd64
    hostname: mongodb3
    ports:
      - "${FORWARD_MONGODB3_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo3_db:/data/db
      - mongo3_configdb:/data/configdb
      - shared-keyfile:/etc/mongo:ro
    command:
      - --bind_ip_all
      - --replSet
      - rs
      - --keyFile
      - /etc/mongo/mongodb-key
    networks:
      - mongo-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  mongo1_db: {}
  mongo1_configdb: {}
  mongo2_db: {}
  mongo2_configdb: {}
  mongo3_db: {}
  mongo3_configdb: {}
  shared-keyfile: {}

networks:
  mongo-net:
    driver: bridge
